Repository roziqinkhoeru/umkmplus, pull requests merged in 2023-06, with the labels that each got.

#132 Feat course
  app/Http/Controllers/CourseEnrollController.php
  composer.lock
  resources/views/user/layout/app.blade.php
Labels: enhancement, user

#134 `fixing` localstorage
  resources/views/admin/blog/index.blade.php
  resources/views/admin/withdraw/index.blade.php
  resources/views/mentor/blog/index.blade.php
Labels: Fix

#135 User view
  resources/views/mentor/courses/detail.blade.php
  resources/views/mentor/courses/edit.blade.php
  resources/views/mentor/courses/media/index.blade.php
  resources/views/mentor/courses/modules/create.blade.php
  resources/views/mentor/courses/modules/edit.blade.php
Labels: Fix

#137 Testing
  black-box-test.txt
  note.txt
  public/assets/img/decoration/card-money.png
  public/assets/img/decoration/wallet-and-money.png
  resources/views/user/layout/app.blade.php
Labels: Fix

#138 Development
  black-box-test.txt
  note.txt
  public/assets/img/decoration/card-money.png
  public/assets/img/decoration/wallet-and-money.png
  resources/views/user/layout/app.blade.php
Labels: Fix

#142 Testing
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/MentorController.php
  resources/views/user/layout/app.blade.php
Labels: admin, mentor, user, Fix

#145 Testing
  database/seeders/CategorySeeder.php
  database/seeders/SpecialistSeeder.php
  resources/views/mentor/courses/edit.blade.php
Labels: user, Fix

#146 Development
  database/seeders/CategorySeeder.php
  database/seeders/SpecialistSeeder.php
  resources/views/mentor/courses/edit.blade.php
Labels: Fix

#147 `fixing` dropdown category mobile
  public/assets/css/app.css
Labels: user, Fix

#149 Testing view
  resources/views/user/courses/index.blade.php
  resources/views/user/courses/indexCategory.blade.php
Labels: enhancement

#150 Development
  resources/views/user/courses/index.blade.php
  resources/views/user/courses/indexCategory.blade.php
Labels: enhancement
